/* This file is generated by scripts/extractAndalusianLanguageCurriculum.py. */
/* Do not edit it by hand: regenerate it from the authenticated BOJA PDF. */

export const ANDALUSIAN_LANGUAGE_CURRICULUM_SOURCE = {
  "source": {
    "title": "Orden de 30 de mayo de 2023 - Educación Primaria de Andalucía - Anexo II",
    "publication": "BOJA núm. 104, de 2 de junio de 2023",
    "cve": "00284747",
    "url": "https://www.juntadeandalucia.es/eboja/2023/104/BOJA23-104-00208-9731-01_00284747.pdf",
    "verificationUrl": "https://www.juntadeandalucia.es/eboja/2023/104/39-verificacion",
    "sha256": "3ace14f41e8ff7a8aa509049291afc506982fca41ce848e9e2daac08c1ce927e",
    "pdfPages": 208,
    "languagePdfPageRange": [
      93,
      118
    ]
  },
  "competences": [
    {
      "code": "1",
      "text": "Reconocer la diversidad lingüística del mundo a partir de la identificación de las lenguas del alumnado y de la realidad plurilingüe y multicultural de España para favorecer la reflexión interlingüística, para identificar y rechazar estereotipos y prejuicios lingüísticos, y para valorar dicha diversidad como fuente de riqueza cultural."
    },
    {
      "code": "2",
      "text": "Comprender e interpretar textos orales y multimodales, identificando el sentido general y la información más relevante, y valorando con ayuda aspectos formales y de contenidos básicos, para construir conocimiento y responder a diferentes necesidades comunicativas."
    },
    {
      "code": "3",
      "text": "Producir textos orales y multimodales, con coherencia, claridad y registro adecuados, para expresar ideas, sentimientos y conceptos; construir conocimiento; establecer vínculos personales; y participar con autonomía y una actitud cooperativa y empática en interacciones orales variadas."
    },
    {
      "code": "4",
      "text": "Comprender e interpretar textos escritos y multimodales, reconociendo el sentido global, las ideas principales y la información explícita e implícita, realizando con ayuda reflexiones elementales sobre aspectos formales y de contenido, para adquirir y construir conocimiento y para responder a necesidades e intereses comunicativos diversos."
    },
    {
      "code": "5",
      "text": "Producir textos escritos y multimodales, con corrección gramatical y ortográfica básicas, secuenciando correctamente los contenidos y aplicando estrategias elementales de planificación, textualización, revisión y edición, para construir conocimiento y para dar respuesta a demandas comunicativas concretas."
    },
    {
      "code": "6",
      "text": "Buscar, seleccionar y contrastar información procedente de dos o más fuentes, de forma planificada y con el debido acompañamiento, evaluando su fiabilidad y reconociendo algunos riesgos de manipulación y desinformación, para transformarla en conocimiento y para comunicarla de manera creativa, adoptando un punto de vista personal y respetuoso con la propiedad intelectual."
    },
    {
      "code": "7",
      "text": "Leer de manera autónoma obras diversas seleccionadas atendiendo a sus gustos e intereses, compartiendo las experiencias de lectura, para iniciar la construcción de la identidad lectora, para fomentar el gusto por la lectura como fuente de placer y para disfrutar de su dimensión social."
    },
    {
      "code": "8",
      "text": "Leer, interpretar y analizar, de manera acompañada, obras o fragmentos literarios adecuados a su desarrollo, estableciendo relaciones entre ellos e identificando el género literario y sus convenciones fundamentales, para iniciarse en el reconocimiento de la literatura como manifestación artística y fuente de placer, conocimiento e inspiración para crear textos de intención literaria."
    },
    {
      "code": "9",
      "text": "Reflexionar de forma guiada sobre el lenguaje a partir de procesos de producción y comprensión de textos en contextos significativos, utilizando la terminología elemental adecuada, para iniciarse en el desarrollo de la conciencia lingüística y para mejorar las destrezas de producción y comprensión oral y escrita."
    },
    {
      "code": "10",
      "text": "Poner las propias prácticas comunicativas al servicio de la convivencia democrática, utilizando un lenguaje no discriminatorio y detectando y rechazando los abusos de poder a través de la palabra, para favorecer un uso no solo eficaz sino también ético del lenguaje."
    }
  ],
  "knowledgeByCycle": {
    "1": [
      {
        "code": "LCL.1.A.1",
        "text": "Biografía lingüística personal y mapa lingüístico del aula."
      },
      {
        "code": "LCL.1.A.2",
        "text": "La diversidad etnocultural y lingüística, con especial atención a las variedades de la modalidad lingüística andaluza en las variedades geográficas más cercanas al alumnado, como riqueza y herramienta de reflexión interlingüística."
      },
      {
        "code": "LCL.1.A.3",
        "text": "Identificación, con acompañamiento, de prejuicios y estereotipos lingüísticos."
      },
      {
        "code": "LCL.1.A.4",
        "text": "Uso de un lenguaje no discriminatorio y respetuoso con las diferencias."
      },
      {
        "code": "LCL.1.B.1.1",
        "text": "Incidencia de los componentes (situación, participantes, intención) en el acto comunicativo; durante las conversaciones, proponiendo temas, aportando opiniones, respondiendo a preguntas y respetando los turnos de palabra y los puntos de vista de los demás."
      },
      {
        "code": "LCL.1.B.2.1",
        "text": "Tipologías textuales: la narración, la descripción y el diálogo."
      },
      {
        "code": "LCL.1.B.2.2",
        "text": "Propiedades textuales: estrategias elementales para la coherencia y la cohesión."
      },
      {
        "code": "LCL.1.B.2.3",
        "text": "Géneros discursivos propios del ámbito personal y educativo. Contenido y forma."
      },
      {
        "code": "LCL.1.B.3.1",
        "text": "Interacción oral: interacción oral adecuada en contextos informales, escucha activa, asertividad, resolución dialogada de conflictos y cortesía lingüística. La expresión y escucha empática de necesidades, vivencias y emociones propias y ajenas para hacer sugerencias o peticiones, pedir o agradecer ayuda, manifestar una queja, formular deseos, expresar alegría o tristeza, saludar o despedirse."
      },
      {
        "code": "LCL.1.B.3.2",
        "text": "Comprensión oral: identificación de las ideas más relevantes e interpretación del sentido global. Detección de usos claramente discriminatorios del lenguaje verbal y no verbal."
      },
      {
        "code": "LCL.1.B.3.3",
        "text": "Producción oral: pronunciación y entonación. Actitud postural. Construcción y comunicación de conocimiento mediante la planificación y producción de textos orales y multimodales sencillos."
      },
      {
        "code": "LCL.1.B.3.4",
        "text": "Comprensión lectora: estrategias elementales de comprensión lectora antes, durante y después de la lectura. Identificación de las ideas más relevantes e interpretación del sentido global. Identificación de elementos gráficos y paratextuales al servicio de la comprensión. Lectura compartida. Detección de usos claramente discriminatorios del lenguaje verbal y no verbal."
      },
      {
        "code": "LCL.1.B.3.5",
        "text": "Producción escrita: convenciones del código escrito y ortografía natural. Coherencia textual. Estrategias elementales, individuales o grupales, de planificación, textualización, revisión y autocorrección. Uso de elementos gráficos y paratextuales elementales. Escritura en soporte digital acompañada. Estrategias elementales, individuales o grupales, de planificación, textualización, revisión y autocorrección de textos. Dibujar lo que se lee, escribir lo que se ve. Uso de elementos gráficos y paratextuales elementales. Escritura en soporte digital acompañada."
      },
      {
        "code": "LCL.1.B.3.6",
        "text": "Alfabetización mediática e informacional: estrategias elementales para la búsqueda guiada de información. Comunicación de la información. Reconocimiento de autoría. Uso guiado de la biblioteca, así como de recursos digitales del aula."
      },
      {
        "code": "LCL.1.C.1",
        "text": "Lectura acompañada de obras o fragmentos variados y diversos de la literatura infantil y de la literatura popular andaluza, adecuados a sus intereses y organizados en itinerarios lectores."
      },
      {
        "code": "LCL.1.C.2",
        "text": "Estrategias para la interpretación acompañada y compartida de las obras a través de conversaciones literarias."
      },
      {
        "code": "LCL.1.C.3",
        "text": "Relación, de manera acompañada, entre los elementos constitutivos esenciales de la obra literaria (tema, personajes, trama, escenario, argumento, espacio) y la construcción acompañada del sentido de la obra."
      },
      {
        "code": "LCL.1.C.4",
        "text": "Relación de los textos leídos y otras manifestaciones artísticas y culturales."
      },
      {
        "code": "LCL.1.C.5",
        "text": "Inicio de la construcción de los itinerarios lectores individuales. Estrategias para la expresión de gustos e intereses."
      },
      {
        "code": "LCL.1.C.6",
        "text": "Lectura expresiva, dramatización o interpretación de fragmentos de la literatura infantil y popular andaluza, atendiendo a los procesos de comprensión y al nivel de desarrollo."
      },
      {
        "code": "LCL.1.C.7",
        "text": "Creación de textos de intención literaria a partir de modelos dados en general, prestando especial atención a la literatura popular andaluza."
      },
      {
        "code": "LCL.1.C.8",
        "text": "Uso acompañado de la biblioteca de aula o de centro como escenario de actividades literarias compartidas, en las que se incluyen las Comunidades lectoras. Los libros ilustrados como fuente de disfrute y de aprendizaje de la lectura, y su conexión con la realidad, con la fantasía y con las demás artes. D. Reflexión sobre la lengua y sus usos en el marco de propuestas de la producción y comprensión de textos orales, escritos o multimodales."
      },
      {
        "code": "LCL.1.D.1",
        "text": "Establecimiento de generalizaciones sobre aspectos lingüísticos elementales a partir de la observación, comparación y transformación de palabras y enunciados, prestando especial atención a la existencia de distintos tipos de palabras y a las relaciones de concordancia que se establecen entre algunas de ellas, utilizando el metalenguaje específico básico."
      },
      {
        "code": "LCL.1.D.2",
        "text": "Diferencias elementales entre lengua oral y lengua escrita. Los sonidos y su escritura. Correspondencias regulares entre fonema y grafía en el ámbito de la ortografía fonética o natural (/k/, z, g, r). Palabras sencillas que contienen los grupos inseparables /bl/- y /br/- y los grupos /m.b/ y /n.v/."
      },
      {
        "code": "LCL.1.D.3",
        "text": "Procedimientos elementales de adquisición de vocabulario. Reflexión contextualizada sobre la relación de significado entre unas palabras y otras. Clases de palabras y concordancias."
      },
      {
        "code": "LCL.1.D.4",
        "text": "Relación entre intención comunicativa y modalidad oracional."
      },
      {
        "code": "LCL.1.D.5",
        "text": "Mecanismos elementales de coherencia y cohesión textual, con especial atención a los conectores temporales y explicativos."
      },
      {
        "code": "LCL.1.D.6",
        "text": "Signos básicos de puntuación como mecanismo para organizar el texto escrito. La utilidad del punto y sus implicaciones ortográficas. Identificación y uso elemental de la coma en las enumeraciones, y de los signos de interrogación y exclamación."
      }
    ],
    "2": [
      {
        "code": "LCL.2.A.1",
        "text": "Biografía lingüística personal y mapa lingüístico del centro."
      },
      {
        "code": "LCL.2.A.2",
        "text": "La diversidad etno-cultural y lingüística, como riqueza y herramienta de reflexión interlingüística. La modalidad lingüística andaluza."
      },
      {
        "code": "LCL.2.A.3",
        "text": "Identificación de prejuicios y estereotipos lingüísticos."
      },
      {
        "code": "LCL.2.A.4",
        "text": "Uso de un lenguaje no discriminatorio y respetuoso con las diferencias."
      },
      {
        "code": "LCL.2.B.1.1",
        "text": "Incidencia de los componentes (situación, participantes, propósito comunicativo, canal) en el acto comunicativo, durante la participación en conversaciones y coloquios, expresando con orden y coherencia opiniones propias, escuchando las de los demás, dando explicaciones y siguiendo las normas establecidas para una correcta comunicación."
      },
      {
        "code": "LCL.2.B.2.1",
        "text": "Tipologías textuales: la narración, la descripción, el diálogo y la exposición."
      },
      {
        "code": "LCL.2.B.2.2",
        "text": "Propiedades textuales: estrategias básicas para la coherencia y la cohesión."
      },
      {
        "code": "LCL.2.B.2.3",
        "text": "Géneros discursivos propios del ámbito personal, social y educativo. Contenido y forma."
      },
      {
        "code": "LCL.2.B.3.1",
        "text": "Interacción oral: interacción oral adecuada en contextos formales e informales, escucha activa, asertividad, resolución dialogada de conflictos y cortesía lingüística. La expresión y escucha empática de necesidades, vivencias y emociones propias y ajenas. Estrategias de interpretación de elementos básicos de la comunicación no verbal (postura, gestos, expresión facial, contacto visual) durante los procesos de interacción y comprensión."
      },
      {
        "code": "LCL.2.B.3.2",
        "text": "Comprensión oral: identificación de las ideas más relevantes e interpretación del sentido global realizando inferencias necesarias. Detección de posibles usos discriminatorios del lenguaje verbal y no verbal."
      },
      {
        "code": "LCL.2.B.3.3",
        "text": "Producción oral: elementos básicos de la prosodia y de la comunicación no verbal. Construcción, comunicación y valoración de conocimiento mediante la planificación y producción de textos orales y multimodales."
      },
      {
        "code": "LCL.2.B.3.4",
        "text": "Comprensión lectora: estrategias de comprensión lectora antes, durante y después de la lectura. Identificación de las ideas más relevantes e interpretación del sentido global realizando las inferencias necesarias. Identificación de elementos gráficos y paratextuales al servicio de la comprensión. Lectura compartida y entonada. Detección de posibles usos discriminatorios del lenguaje verbal y no verbal. Lectura individual de textos breves, narrativos, poéticos… con entonación, fluidez, ritmo y respeto hacia los signos de puntuación (punto, coma, punto y coma, puntos suspensivos, signos de admiración e interrogación)."
      },
      {
        "code": "LCL.2.B.3.5",
        "text": "Producción escrita: convenciones del código escrito y ortografía reglada básica. Coherencia y cohesión textual. Estrategias básicas, individuales o grupales, de planificación, textualización, revisión y autocorrección. Uso de elementos gráficos y paratextuales básicos al servicio de la comprensión. Escritura en soporte digital acompañada."
      },
      {
        "code": "LCL.2.B.3.6",
        "text": "Alfabetización mediática e informacional: estrategias básicas para la búsqueda guiada de información en fuentes documentales variadas y con distintos soportes y formatos. Reconocimiento de autoría. Comparación y comunicación creativa de la información. Uso de la biblioteca, así como de recursos digitales del aula."
      },
      {
        "code": "LCL.2.C.1",
        "text": "Lectura acompañada de obras o fragmentos variados y diversos de la literatura infantil y de la literatura popular andaluza, adecuados a sus intereses y organizados en itinerarios lectores."
      },
      {
        "code": "LCL.2.C.2",
        "text": "Estrategias básicas para la interpretación acompañada y compartida de las obras a través de conversaciones literarias."
      },
      {
        "code": "LCL.2.C.3",
        "text": "Relación, de manera acompañada, entre los elementos constitutivos esenciales de la obra literaria (tema, protagonistas, personajes secundarios, trama, escenario, lenguaje, argumento, espacio) y la construcción del sentido de la obra."
      },
      {
        "code": "LCL.2.C.4",
        "text": "Análisis guiado de los recursos expresivos y sus efectos en la recepción del texto."
      },
      {
        "code": "LCL.2.C.5",
        "text": "Relación entre los textos leídos y otras manifestaciones artísticas y culturales."
      },
      {
        "code": "LCL.2.C.6",
        "text": "Construcción de la identidad lectora. Estrategias para la expresión de gustos e intereses e iniciación a la valoración argumentada de las obras."
      },
      {
        "code": "LCL.2.C.7",
        "text": "Lectura expresiva, dramatización o interpretación de fragmentos de la literatura infantil, prestando especial atención a la literatura popular andaluza, atendiendo a los procesos de comprensión y al nivel de desarrollo."
      },
      {
        "code": "LCL.2.C.8",
        "text": "Creación de textos de intención literaria de manera libre, a partir de modelos dados o recreando textos literarios en general, con especial atención a la literatura popular andaluza.."
      },
      {
        "code": "LCL.2.C.9",
        "text": "Uso acompañado de la biblioteca de aula o de centro como escenario de actividades literarias compartidas. Comunidades lectoras. D. Reflexión sobre la lengua y sus usos en el marco de propuestas de producción y comprensión de textos orales, escritos o multimodales."
      },
      {
        "code": "LCL.2.D.1",
        "text": "Establecimiento de generalizaciones sobre aspectos lingüísticos elementales a partir de la observación, comparación y transformación de enunciados, prestando especial atención a las relaciones que se establecen entre sustantivos, adjetivos y verbos."
      },
      {
        "code": "LCL.2.D.2",
        "text": "Aproximación a la lengua como sistema con distintos niveles: sonidos y letras, palabras, oraciones y textos. Observación y comparación de unidades comunicativas básicas. Reglas ortográficas (b/v, g/j, ll/y, r/rr, h; c/qu, z/c, d/z, s/z) en palabras de uso frecuente."
      },
      {
        "code": "LCL.2.D.3",
        "text": "Procedimientos elementales de adquisición de vocabulario. Similitudes y diferencias de forma y significado entre palabras de la misma familia léxica o semántica. Clases de palabras: sustantivos, artículos y otros determinantes, pronombres personales básicos, adjetivos calificativos y verbos."
      },
      {
        "code": "LCL.2.D.4",
        "text": "Relación entre intención comunicativa y modalidad oracional."
      },
      {
        "code": "LCL.2.D.5",
        "text": "Mecanismos elementales de coherencia y cohesión, con especial atención a las repeticiones y sinónimos, y al orden de oraciones y párrafos."
      },
      {
        "code": "LCL.2.D.6",
        "text": "Los signos de puntuación como mecanismos para organizar el texto escrito y para expresar la intención comunicativa."
      },
      {
        "code": "LCL.2.D.7",
        "text": "Estrategias elementales para el uso guiado de diccionarios, en distintos soportes."
      }
    ],
    "3": [
      {
        "code": "LCL.3.A.1",
        "text": "Biografía lingüística personal y mapa lingüístico del entorno geográfico. Mapa del español en el mundo. El español como lengua universal. La Real Academia Española de la lengua. Orígenes e historia de la lengua española. Lenguas muertas en España: griego y latín. Elio Antonio de Nebrija como autor de la primera gramática de la Lengua Castellana."
      },
      {
        "code": "LCL.3.A.2",
        "text": "La diversidad etnocultural y lingüística como riqueza y herramienta de reflexión interlingüística. Aproximación a las lenguas de signos. La modalidad lingüística andaluza."
      },
      {
        "code": "LCL.3.A.3",
        "text": "Estrategias de identificación de prejuicios y estereotipos lingüísticos."
      },
      {
        "code": "LCL.3.A.4",
        "text": "Uso de un lenguaje no discriminatorio y respetuoso con las diferencias."
      },
      {
        "code": "LCL.3.B.1.1",
        "text": "Interacciones entre los componentes del hecho comunicativo (situación, participantes, propósito comunicativo, canal, registro)."
      },
      {
        "code": "LCL.3.B.2.1",
        "text": "Tipologías textuales: la narración, la descripción, el diálogo, la exposición y la argumentación."
      },
      {
        "code": "LCL.3.B.2.2",
        "text": "Propiedades textuales: estrategias básicas para la coherencia, cohesión y adecuación."
      },
      {
        "code": "LCL.3.B.2.3",
        "text": "Géneros discursivos propios del ámbito personal, social y educativo. Contenido y forma. Redes sociales y sus riesgos."
      },
      {
        "code": "LCL.3.B.3.1",
        "text": "Interacción oral: interacción oral y adecuada en contextos formales e informales, escucha activa, asertividad, resolución dialogada de conflictos y cortesía lingüística. La expresión y escucha empática de necesidades, vivencias y emociones propias y ajenas."
      },
      {
        "code": "LCL.3.B.3.2",
        "text": "Comprensión oral: identificación de las ideas más relevantes e interpretación del sentido global realizando las inferencias necesarias. Valoración crítica. Detección de usos discriminatorios del lenguaje verbal y no verbal. Estrategias de uso gradualmente autónomo de recursos lingüísticos diversos en diferentes soportes, incluidos los digitales, para mejorar la comprensión de textos."
      },
      {
        "code": "LCL.3.B.3.3",
        "text": "Producción oral: elementos de la prosodia y de la comunicación no verbal. Construcción, comunicación y valoración crítica de conocimiento mediante la planificación y producción de textos orales y multimodales con progresiva autonomía."
      },
      {
        "code": "LCL.3.B.3.4",
        "text": "Comprensión lectora: estrategias de comprensión lectora antes, durante y después de la lectura. Identificación de las ideas más relevantes e interpretación del sentido global realizando las inferencias necesarias. Valoración crítica. Identificación de elementos gráficos y paratextuales al servicio de la comprensión. Lectura compartida y expresiva. Detección de usos discriminatorios del lenguaje verbal y no verbal."
      },
      {
        "code": "LCL.3.B.3.5",
        "text": "Producción escrita: ortografía reglada en la textualización y la autocorrección. Coherencia, cohesión y adecuación textual. Estrategias básicas, individuales o grupales, de planificación, textualización, revisión y autocorrección. Uso de elementos gráficos y paratextuales al servicio de la comprensión. Escritura en soporte digital acompañada."
      },
      {
        "code": "LCL.3.B.3.6",
        "text": "Alfabetización mediática e informacional: estrategias para la búsqueda de información en distintas fuentes documentales y con distintos soportes y formatos. Reconocimiento de autoría. Comparación, organización, valoración crítica y comunicación creativa de la información. Uso progresivamente autónomo de la biblioteca, así como de recursos digitales del aula."
      },
      {
        "code": "LCL.3.C.1",
        "text": "Lectura progresivamente autónoma de obras o fragmentos variados y diversos de la literatura y de la literatura popular andaluza, adecuados a su edad y organizados en itinerarios lectores."
      },
      {
        "code": "LCL.3.C.2",
        "text": "Estrategia para la interpretación acompañada y compartida de las obras a través de conversaciones literarias."
      },
      {
        "code": "LCL.3.C.3",
        "text": "Relación, de manera acompañada, entre los elementos constitutivos de la obra literaria (tema, protagonistas, personajes secundarios, argumento, espacio) y la construcción del sentido de la obra."
      },
      {
        "code": "LCL.3.C.4",
        "text": "Análisis acompañado de la relación entre los elementos básicos del género literario y la construcción del sentido de la obra. Características fundamentales de textos literarios narrativos, poéticos y dramáticos."
      },
      {
        "code": "LCL.3.C.5",
        "text": "Estrategias básicas para la interpretación progresivamente autónoma de los textos literarios. El lenguaje figurado (símiles y metáforas), las personificaciones, las hipérboles y los juegos de palabras. Refranes, aforismos y greguerías para profundizar en el sentido y posibilidades del lenguaje. El uso de comparaciones, metáforas, aumentativos, diminutivos y sinónimos en textos literarios."
      },
      {
        "code": "LCL.3.C.6",
        "text": "Relación entre los textos leídos y otras manifestaciones artísticas y culturales. Los libros ilustrados como fuente de disfrute y de aprendizaje de la lectura y su conexión con la realidad, con la fantasía y con las demás artes."
      },
      {
        "code": "LCL.3.C.7",
        "text": "Progreso en la construcción de la identidad lectora. Estrategias para la expresión de gustos e intereses y para la valoración crítica elemental de las obras."
      },
      {
        "code": "LCL.3.C.8",
        "text": "Lectura expresiva, dramatización o interpretación de fragmentos, de la literatura infantil y de la literatura popular andaluza, atendiendo a los procesos de comprensión y al nivel de desarrollo. Principales autores de la literatura española y universal en las distintas épocas. Obras más relevantes."
      },
      {
        "code": "LCL.3.C.9",
        "text": "Creación de textos de intención literaria, de manera libre y a partir de la recreación y apropiación de los modelos dados en general, con especial atención a la literatura popular andaluzar."
      },
      {
        "code": "LCL.3.C.10",
        "text": "Uso progresivamente autónomo de la biblioteca de aula o de centro como escenario de actividades literarias compartidas. Comunidades lectoras. D. Reflexión sobre la lengua y sus usos en el marco de propuestas de producción y comprensión de textos orales, escritos o multimodales."
      },
      {
        "code": "LCL.3.D.1",
        "text": "Establecimiento de generalizaciones sobre aspectos lingüísticos elementales a partir de la observación, comparación y transformación de palabras y enunciados."
      },
      {
        "code": "LCL.3.D.2",
        "text": "Aproximación a la lengua como sistema con distintos niveles: sonidos y letras, palabras, oraciones y textos. Observación y comparación de unidades comunicativas básicas. Relaciones fundamentales entre los esquemas semánticos y sintácticos de la oración. Uso de la sintaxis correcta en los escritos propios. Reconocimiento de sintagmas sencillos."
      },
      {
        "code": "LCL.3.D.3",
        "text": "Procedimientos básicos de adquisición de vocabulario. Mecanismos léxicos básicos para la formación de palabras. Familias de palabras, palabras derivadas, homónimas."
      },
      {
        "code": "LCL.3.D.4",
        "text": "Relación entre intención comunicativa y modalidad oracional."
      },
      {
        "code": "LCL.3.D.5",
        "text": "Mecanismos básicos de coherencia y cohesión, con especial atención a las sustituciones pronominales y a la correlación temporal establecida mediante los distintos tiempos verbales. Conjugación de los verbos. La voz pasiva."
      },
      {
        "code": "LCL.3.D.6",
        "text": "Estrategias de observación y formulación de generalizaciones sobre la acentuación."
      },
      {
        "code": "LCL.3.D.7",
        "text": "Los signos de puntuación como mecanismos para organizar el texto y expresar intención comunicativa."
      },
      {
        "code": "LCL.3.D.8",
        "text": "Estrategias básicas para el uso progresivamente autónomo de diccionarios, en distintos soportes."
      }
    ]
  },
  "criteriaByCourse": {
    "1": [
      {
        "code": "1.1.a",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto por las distintas lenguas y variedades dialectales de su entorno más cercano, reconociendo las lenguas de signos.",
        "knowledgeCodes": [
          "LCL.1.A.1",
          "LCL.1.B.1.1"
        ]
      },
      {
        "code": "1.2.a",
        "competenceCode": "1",
        "text": "Iniciar de manera acompañada el reconocimiento y en contextos próximos, de algunos prejuicios y estereotipos lingüísticos y culturales muy frecuentes, a partir de modelos dados.",
        "knowledgeCodes": [
          "LCL.1.A.3",
          "LCL.1.B.1.1"
        ]
      },
      {
        "code": "1.3.a",
        "competenceCode": "1",
        "text": "Iniciarse en el reconocimiento de los rasgos de la modalidad lingüística y de las tradiciones literarias populares andaluzas.",
        "knowledgeCodes": [
          "LCL.1.A.2"
        ]
      },
      {
        "code": "2.1.a",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales y los mensajes explícitos.",
        "knowledgeCodes": [
          "LCL.1.B.2.3",
          "LCL.1.B.3.2"
        ]
      },
      {
        "code": "3.1.a",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales sencillos, con planificación acompañada a partir de modelos dados.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.B.3.3"
        ]
      },
      {
        "code": "3.2.a",
        "competenceCode": "3",
        "text": "Participar en interacciones orales, a partir de modelos dados utilizando algunas normas básicas de la cortesía lingüística.",
        "knowledgeCodes": [
          "LCL.1.B.3.1"
        ]
      },
      {
        "code": "3.3.a",
        "competenceCode": "3",
        "text": "Reproducir textos orales sencillos de la literatura infantil andaluza del entorno cercano del alumnado.",
        "knowledgeCodes": [
          "LCL.1.C.1",
          "LCL.1.C.6"
        ]
      },
      {
        "code": "4.1.a",
        "competenceCode": "4",
        "text": "Leer textos escritos y multimodales adecuados a su desarrollo cognitivo, identificando el sentido global y la información relevante y movilizando de forma acompañada estrategias básicas de comprensión, para adquirir conocimiento.",
        "knowledgeCodes": [
          "LCL.1.B.3.4",
          "LCL.1.D.3"
        ]
      },
      {
        "code": "4.2.a",
        "competenceCode": "4",
        "text": "Identificar, de manera acompañada, el contenido y aspectos formales y no formales elementales de textos escritos y multimodales sencillos.",
        "knowledgeCodes": [
          "LCL.1.B.2.1",
          "LCL.1.B.3.4",
          "LCL.1.D.4"
        ]
      },
      {
        "code": "5.1.a",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales sencillos y coherentes, desde las diferentes etapas del proceso evolutivo de la escritura, ajustándose a modelos dados.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.B.2.3",
          "LCL.1.B.3.5",
          "LCL.1.D.6"
        ]
      },
      {
        "code": "6.1.a",
        "competenceCode": "6",
        "text": "Iniciarse en la búsqueda de resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal, realizado de manera acompañada, que implique la localización y selección de información de dos o más fuentes, atendiendo a modelos, incluidas las digitales.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "6.2.a",
        "competenceCode": "6",
        "text": "Compartir los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal orientado y realizado de manera acompañada.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "6.3.a",
        "competenceCode": "6",
        "text": "Iniciarse de manera acompañada en el uso, seguro y saludable de las tecnologías digitales en relación con la búsqueda de la información.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "7.1.a",
        "competenceCode": "7",
        "text": "Iniciarse en la lectura de textos de distintos autores y autoras acordes con sus gustos e intereses, seleccionados de manera acompañada, desde las diferentes etapas del proceso evolutivo de la lectura.",
        "knowledgeCodes": [
          "LCL.1.B.3.6",
          "LCL.1.C.1"
        ]
      },
      {
        "code": "7.2.a",
        "competenceCode": "7",
        "text": "Compartir oralmente la experiencia de lectura iniciándose en la participación en comunidades lectoras de ámbito escolar para conseguir disfrutar de la dimensión social de la lectura.",
        "knowledgeCodes": [
          "LCL.1.B.3.4",
          "LCL.1.C.5",
          "LCL.1.C.8"
        ]
      },
      {
        "code": "8.1.a",
        "competenceCode": "8",
        "text": "Escuchar e iniciar la lectura de textos orales y escritos de la literatura infantil, que recojan diversidad de autores y autoras, estableciendo de manera acompañada relaciones elementales entre ellos y con otras manifestaciones artísticas o culturales.",
        "knowledgeCodes": [
          "LCL.1.C.1",
          "LCL.1.C.4"
        ]
      },
      {
        "code": "8.2.a",
        "competenceCode": "8",
        "text": "Reproducir, de manera acompañada, textos sencillos individuales o colectivos con intención literaria, adaptados a las diferentes etapas del proceso evolutivo de la escritura, a partir de modelos dados y en distintos soportes.",
        "knowledgeCodes": [
          "LCL.1.C.3",
          "LCL.1.C.7",
          "LCL.1.D.5"
        ]
      },
      {
        "code": "8.3.a",
        "competenceCode": "8",
        "text": "Conocer pequeños textos literarios como las retahílas tradicionales andaluzas.",
        "knowledgeCodes": [
          "LCL.1.C.2"
        ]
      },
      {
        "code": "9.1.a",
        "competenceCode": "9",
        "text": "Iniciarse en la reflexión sobre el funcionamiento de la lengua, prestando especial atención a la concordancia y a las relaciones de significado entre las palabras, a partir de la observación, comparación y manipulación de palabras, en un proceso acompañado de comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.1.D.1",
          "LCL.1.D.2"
        ]
      },
      {
        "code": "9.2.a",
        "competenceCode": "9",
        "text": "Revisar los textos propios y subsanar algunos problemas de comprensión lectora, de manera acompañada, usando la terminología lingüística básica adecuada.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.D.3",
          "LCL.1.D.5",
          "LCL.1.D.6"
        ]
      },
      {
        "code": "10.1.a",
        "competenceCode": "10",
        "text": "Identificar los usos lingüísticos discriminatorios identificados a partir de la reflexión grupal acompañada sobre los aspectos elementales, verbales, de la comunicación, teniendo en cuenta una perspectiva de género.",
        "knowledgeCodes": [
          "LCL.1.A.4",
          "LCL.1.B.3.2",
          "LCL.1.B.3.4"
        ]
      },
      {
        "code": "10.2.a",
        "competenceCode": "10",
        "text": "Identificar, con la planificación y el acompañamiento necesarios, estrategias elementales para la escucha activa y el consenso, iniciándose en la gestión dialogada de conflictos.",
        "knowledgeCodes": [
          "LCL.1.B.1.1",
          "LCL.1.B.3.1"
        ]
      }
    ],
    "2": [
      {
        "code": "1.1.b",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto a las distintas lenguas y variedades dialectales de su entorno, valorando la igualdad en las diferencias.",
        "knowledgeCodes": [
          "LCL.1.A.1",
          "LCL.1.B.1.1"
        ]
      },
      {
        "code": "1.2.b",
        "competenceCode": "1",
        "text": "Reconocer, de manera acompañada y en contextos próximos, algunos prejuicios y estereotipos lingüísticos y culturales muy frecuentes.",
        "knowledgeCodes": [
          "LCL.1.A.3",
          "LCL.1.B.1.1"
        ]
      },
      {
        "code": "1.3.b",
        "competenceCode": "1",
        "text": "Reconocer rasgos de la modalidad lingüística y de las tradiciones literarias populares andaluzas.",
        "knowledgeCodes": [
          "LCL.1.A.2"
        ]
      },
      {
        "code": "2.1.b",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales y los mensajes explícitos y los mensajes implícitos más sencillos, e iniciando, de manera acompañada, la valoración del contenido y de los elementos no verbales más elementales.",
        "knowledgeCodes": [
          "LCL.1.B.2.3",
          "LCL.1.B.3.2"
        ]
      },
      {
        "code": "3.1.b",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales coherentes, con planificación acompañada y utilizando recursos no verbales elementales.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.B.3.3"
        ]
      },
      {
        "code": "3.2.b",
        "competenceCode": "3",
        "text": "Participar en interacciones orales espontáneas, incorporando estrategias elementales de escucha activa y de cortesía lingüística.",
        "knowledgeCodes": [
          "LCL.1.B.3.1"
        ]
      },
      {
        "code": "3.3.b",
        "competenceCode": "3",
        "text": "Reproducir textos orales sencillos de la literatura infantil andaluza.",
        "knowledgeCodes": [
          "LCL.1.C.1",
          "LCL.1.C.6"
        ]
      },
      {
        "code": "4.1.b",
        "competenceCode": "4",
        "text": "Comprender el sentido global y la información relevante de textos cercanos, escritos y multimodales, a partir de estrategias básicas de comprensión antes, durante y después de la lectura.",
        "knowledgeCodes": [
          "LCL.1.B.3.4",
          "LCL.1.D.3"
        ]
      },
      {
        "code": "4.2.b",
        "competenceCode": "4",
        "text": "Analizar, de manera acompañada, el contenido y aspectos formales y no formales elementales de textos escritos y multimodales sencillos, valorando su contenido y estructura.",
        "knowledgeCodes": [
          "LCL.1.B.2.1",
          "LCL.1.B.3.4",
          "LCL.1.D.4"
        ]
      },
      {
        "code": "5.1.b",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales sencillos y coherentes en distintos soportes, desde las diferentes etapas del proceso evolutivo de la escritura, ajustándose a modelos dados y movilizando, de manera acompañada, estrategias elementales, individuales o grupales, de planificación, textualización y revisión.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.B.2.3",
          "LCL.1.B.3.5",
          "LCL.1.D.6"
        ]
      },
      {
        "code": "6.1.b",
        "competenceCode": "6",
        "text": "Localizar, seleccionar y contrastar información de distintas fuentes, incluidas las digitales, citándolas y recreándolas mediante la adaptación creativa de modelos dados.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "6.2.b",
        "competenceCode": "6",
        "text": "Compartir los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal, realizado de manera acompañada.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "6.3.b",
        "competenceCode": "6",
        "text": "Adoptar hábitos de uso crítico, seguro, sostenible y saludable de las tecnologías digitales en relación con la búsqueda y la comunicación de la información.",
        "knowledgeCodes": [
          "LCL.1.B.3.6"
        ]
      },
      {
        "code": "7.1.b",
        "competenceCode": "7",
        "text": "Leer con progresiva autonomía textos de distintos autores y autoras acordes con sus gustos e intereses, seleccionados de manera acompañada, desde las diferentes etapas del proceso evolutivo de la lectura.",
        "knowledgeCodes": [
          "LCL.1.B.3.6",
          "LCL.1.C.1"
        ]
      },
      {
        "code": "7.2.b",
        "competenceCode": "7",
        "text": "Compartir oralmente la experiencia y disfrute por la lectura, participando en comunidades lectoras de ámbito escolar.",
        "knowledgeCodes": [
          "LCL.1.B.3.4",
          "LCL.1.C.5",
          "LCL.1.C.8"
        ]
      },
      {
        "code": "8.1.b",
        "competenceCode": "8",
        "text": "Escuchar y leer de manera acompañada textos orales y escritos de la literatura infantil, que recojan diversidad de autores y autoras, estableciendo de manera acompañada relaciones elementales entre ellos y con otras manifestaciones artísticas o culturales.",
        "knowledgeCodes": [
          "LCL.1.C.1",
          "LCL.1.C.4"
        ]
      },
      {
        "code": "8.2.b",
        "competenceCode": "8",
        "text": "Producir, de manera acompañada, textos sencillos individuales o colectivos con intención literaria, adaptados a las diferentes etapas del proceso evolutivo de la escritura, ajustándose a modelos dados, en distintos soportes y complementándolos con otros lenguajes artísticos.",
        "knowledgeCodes": [
          "LCL.1.C.3",
          "LCL.1.C.7",
          "LCL.1.D.5"
        ]
      },
      {
        "code": "8.3.b",
        "competenceCode": "8",
        "text": "Conocer e interpretar pequeños textos literarios a partir de pautas y modelos dados como las retahílas tradicionales andaluzas.",
        "knowledgeCodes": [
          "LCL.1.C.2"
        ]
      },
      {
        "code": "9.1.b",
        "competenceCode": "9",
        "text": "Formular conclusiones elementales sobre el funcionamiento de la lengua, prestando especial atención a la concordancia y a las relaciones de significado entre las palabras, a partir de la observación, comparación y transformación de palabras y enunciados, en un proceso acompañado de producción o comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.1.D.1",
          "LCL.1.D.2"
        ]
      },
      {
        "code": "9.2.b",
        "competenceCode": "9",
        "text": "Revisar y mejorar los textos propios y subsanar algunos problemas de comprensión lectora, de manera acompañada, a partir de la reflexión metalingüística e interlingüística y usando la terminología lingüística básica adecuada.",
        "knowledgeCodes": [
          "LCL.1.B.2.2",
          "LCL.1.D.3",
          "LCL.1.D.5",
          "LCL.1.D.6"
        ]
      },
      {
        "code": "10.1.b",
        "competenceCode": "10",
        "text": "Rechazar los usos lingüísticos discriminatorios identificados a partir de la reflexión grupal acompañada sobre los aspectos elementales, verbales y no verbales, de la comunicación, teniendo en cuenta una perspectiva de género",
        "knowledgeCodes": [
          "LCL.1.A.4",
          "LCL.1.B.3.2",
          "LCL.1.B.3.4"
        ]
      },
      {
        "code": "10.2.b",
        "competenceCode": "10",
        "text": "Movilizar, con la planificación y el acompañamiento necesarios, estrategias elementales para la escucha activa, la comunicación asertiva y el consenso, iniciándose en la gestión dialogada de conflictos.",
        "knowledgeCodes": [
          "LCL.1.B.1.1",
          "LCL.1.B.3.1"
        ]
      }
    ],
    "3": [
      {
        "code": "1.1.a",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto por las distintas lenguas y variedades dialectales de su entorno, incluidas las lenguas de signos, identificando algunas palabras sencillas de uso cotidiano.",
        "knowledgeCodes": [
          "LCL.2.A.1",
          "LCL.2.A.2",
          "LCL.2.B.1.1"
        ]
      },
      {
        "code": "1.2.a",
        "competenceCode": "1",
        "text": "Identificar en contextos próximos, a partir de modelos dados, prejuicios y estereotipos lingüísticos frecuentes, reconociendo la pluralidad lingüística de su entorno como una fuente de riqueza cultural.",
        "knowledgeCodes": [
          "LCL.2.A.2",
          "LCL.2.A.3",
          "LCL.2.A.4"
        ]
      },
      {
        "code": "1.3.a",
        "competenceCode": "1",
        "text": "Identificar y reconocer de manera acompañada rasgos de la modalidad lingüística andaluza.",
        "knowledgeCodes": [
          "LCL.2.A.1",
          "LCL.2.A.2",
          "LCL.2.A.3"
        ]
      },
      {
        "code": "2.1.a",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales, los mensajes explícitos y los mensajes implícitos más sencillos, iniciando, de manera acompañada, la valoración crítica del contenido y de los elementos no verbales elementales.",
        "knowledgeCodes": [
          "LCL.2.B.2.3",
          "LCL.2.B.3.2",
          "LCL.2.B.3.4",
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "3.1.a",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales coherentes, con planificación acompañada y a partir de modelos dados, ajustando el discurso a la situación comunicativa y utilizando recursos no verbales básicos.",
        "knowledgeCodes": [
          "LCL.2.B.2.2",
          "LCL.2.B.3.3"
        ]
      },
      {
        "code": "3.2.a",
        "competenceCode": "3",
        "text": "Participar en interacciones orales espontáneas, respetando las normas básicas de la cortesía lingüística e iniciándose en estrategias de escucha activa.",
        "knowledgeCodes": [
          "LCL.2.B.3.1"
        ]
      },
      {
        "code": "3.3.a",
        "competenceCode": "3",
        "text": "Conocer y producir textos orales y multimodales sencillos con planificación acompañada, propios de la literatura infantil andaluza, a partir de modelos dados.",
        "knowledgeCodes": [
          "LCL.2.B.3.3"
        ]
      },
      {
        "code": "4.1.a",
        "competenceCode": "4",
        "text": "Leer de manera silenciosa y en voz alta textos escritos y multimodales sencillos, identificando el sentido global y la información relevante para construir conocimiento.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.D.6"
        ]
      },
      {
        "code": "4.2.a",
        "competenceCode": "4",
        "text": "Analizar, de manera acompañada, el contenido y aspectos formales y no verbales elementales de textos escritos y multimodales, valorando su contenido y estructura e iniciándose en la evaluación de su fiabilidad, para responder a necesidades comunicativas concretas.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "5.1.a",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales sencillos y coherentes, en distintos soportes, para diferentes modelos discursivos, iniciándose en el uso de las normas gramaticales y ortográficas más sencillas y progresando, de manera acompañada, en la movilización de estrategias sencillas, individuales o grupales, de planificación, redacción, revisión y edición.",
        "knowledgeCodes": [
          "LCL.2.A.4",
          "LCL.2.B.3.5",
          "LCL.2.D.5",
          "LCL.2.D.4"
        ]
      },
      {
        "code": "6.1.a",
        "competenceCode": "6",
        "text": "Localizar y seleccionar información de distintas fuentes, incluidas las digitales, para un proceso de investigación, e iniciarse en procesos para contrastar los resultados, citándolas y recreándolas mediante la adaptación de modelos dados.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "6.2.a",
        "competenceCode": "6",
        "text": "Compartir los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal o ecosocial orientado y realizado de manera acompañada.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "6.3.a",
        "competenceCode": "6",
        "text": "Adoptar, de manera acompañada, hábitos sencillos de uso crítico, seguro, sostenible y saludable de las tecnologías digitales en relación con la búsqueda y la comunicación de la información.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "7.1.a",
        "competenceCode": "7",
        "text": "Leer de manera autónoma o acompañada textos de diversos autores y autoras, ajustados a sus gustos e intereses y seleccionados con creciente autonomía, avanzando en la construcción de su identidad lectora para conseguir que sea una fuente de placer.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.B.3.6",
          "LCL.2.C.1",
          "LCL.2.C.6"
        ]
      },
      {
        "code": "7.2.a",
        "competenceCode": "7",
        "text": "Compartir la experiencia de lectura, en soportes sencillos, participando en comunidades lectoras en el ámbito escolar para conseguir disfrutar de la dimensión social de la lectura.",
        "knowledgeCodes": [
          "LCL.2.C.2",
          "LCL.2.C.7",
          "LCL.2.C.9"
        ]
      },
      {
        "code": "8.1.a",
        "competenceCode": "8",
        "text": "Escuchar y leer de manera acompañada textos variados de la literatura infantil universal, que recojan diversidad de autores y autoras, relacionándolos en función de los temas y con otras manifestaciones artísticas o culturales de manera acompañada.",
        "knowledgeCodes": [
          "LCL.2.C.1",
          "LCL.2.C.3",
          "LCL.2.C.5",
          "LCL.2.C.4",
          "LCL.2.C.7"
        ]
      },
      {
        "code": "8.2.a",
        "competenceCode": "8",
        "text": "Producir, de manera acompañada, textos sencillos individuales o colectivos con intención literaria, recreando de manera personal los modelos dados, y complementándolos con otros lenguajes artísticos.",
        "knowledgeCodes": [
          "LCL.2.C.1",
          "LCL.2.C.3",
          "LCL.2.C.5",
          "LCL.2.C.8",
          "LCL.2.D.5",
          "LCL.2.D.6"
        ]
      },
      {
        "code": "8.3.a",
        "competenceCode": "8",
        "text": "Conocer pequeños textos literarios de la literatura tradicional andaluza.",
        "knowledgeCodes": [
          "LCL.2.B.2.1",
          "LCL.2.C.7"
        ]
      },
      {
        "code": "9.1.a",
        "competenceCode": "9",
        "text": "Formular conclusiones elementales sobre el funcionamiento de la lengua, prestando especial atención a la relación entre el sujeto y el verbo, a partir de la observación, comparación y manipulación de palabras, enunciados y textos, en un proceso acompañado de producción o comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.2.D.1",
          "LCL.2.D.2"
        ]
      },
      {
        "code": "9.2.a",
        "competenceCode": "9",
        "text": "Revisar y mejorar los textos propios y ajenos y subsanar algunos problemas de comprensión lectora, de manera acompañada, a partir de la reflexión metalingüística y usando la terminología básica adecuada.",
        "knowledgeCodes": [
          "LCL.2.B.2.3",
          "LCL.2.B.3.5",
          "LCL.2.D.3",
          "LCL.2.D.5",
          "LCL.2.D.6",
          "LCL.2.D.7"
        ]
      },
      {
        "code": "10.1.a",
        "competenceCode": "10",
        "text": "Rechazar los usos lingüísticos discriminatorios e iniciar la identificación de los abusos de poder a través de la palabra a partir de la reflexión grupal acompañada sobre los aspectos básicos, verbales y no verbales, de la comunicación, teniendo en cuenta una perspectiva de género.",
        "knowledgeCodes": [
          "LCL.2.A.4",
          "LCL.2.B.3.1",
          "LCL.2.B.3.2",
          "LCL.2.B.3.4"
        ]
      },
      {
        "code": "10.2.a",
        "competenceCode": "10",
        "text": "Iniciar, con la planificación y el acompañamiento necesarios, estrategias básicas para la comunicación asertiva y el consenso, progresando en la gestión dialogada de conflictos.",
        "knowledgeCodes": [
          "LCL.2.B.1.1",
          "LCL.2.B.3.1"
        ]
      }
    ],
    "4": [
      {
        "code": "1.1.b",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto a las distintas lenguas y variedades dialectales de su entorno, identificando algunas expresiones de uso cotidiano.",
        "knowledgeCodes": [
          "LCL.2.A.1",
          "LCL.2.A.2",
          "LCL.2.B.1.1"
        ]
      },
      {
        "code": "1.2.b",
        "competenceCode": "1",
        "text": "Identificar, con cierta autonomía y en contextos próximos, prejuicios y estereotipos lingüísticos frecuentes, aportando alternativas y reconociendo la diversidad lingüística de su entorno como una fuente de riqueza cultural.",
        "knowledgeCodes": [
          "LCL.2.A.2",
          "LCL.2.A.3",
          "LCL.2.A.4"
        ]
      },
      {
        "code": "1.3.b",
        "competenceCode": "1",
        "text": "Identificar y reconocer rasgos de la modalidad lingüística andaluza, con especial atención a la variedades del entorno del alumnado.",
        "knowledgeCodes": [
          "LCL.2.A.1",
          "LCL.2.A.2",
          "LCL.2.A.3"
        ]
      },
      {
        "code": "2.1.b",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales, los mensajes explícitos y los mensajes implícitos más sencillos, y progresando, de manera acompañada, en la valoración crítica del contenido y de los elementos no verbales elementales.",
        "knowledgeCodes": [
          "LCL.2.B.2.3",
          "LCL.2.B.3.2",
          "LCL.2.B.3.4",
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "3.1.b",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales coherentes, con planificación acompañada, ajustando el discurso a la situación comunicativa y utilizando recursos no verbales básicos.",
        "knowledgeCodes": [
          "LCL.2.B.2.2",
          "LCL.2.B.3.3"
        ]
      },
      {
        "code": "3.2.b",
        "competenceCode": "3",
        "text": "Participar en interacciones orales espontáneas o regladas, incorporando estrategias básicas de escucha activa y cortesía lingüística.",
        "knowledgeCodes": [
          "LCL.2.B.3.1"
        ]
      },
      {
        "code": "3.3.b",
        "competenceCode": "3",
        "text": "Conocer y producir textos orales y multimodales con planificación acompañada, propios de la literatura infantil andaluza.",
        "knowledgeCodes": [
          "LCL.2.B.3.3"
        ]
      },
      {
        "code": "4.1.b",
        "competenceCode": "4",
        "text": "Comprender el sentido global y la información relevante de textos sencillos, escritos y multimodales, realizando inferencias a partir de estrategias básicas de comprensión antes, durante y después de la lectura.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.D.6"
        ]
      },
      {
        "code": "4.2.b",
        "competenceCode": "4",
        "text": "Analizar, de manera acompañada, el contenido y aspectos formales y no formales elementales de textos escritos y multimodales, valorando su contenido y estructura e iniciándose en la evaluación de su fiabilidad.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "5.1.b",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales sencillos, con coherencia y adecuación, en distintos soportes, seleccionando el modelo discursivo que mejor responda a cada situación comunicativa, iniciándose en el uso de las normas gramaticales y ortográficas más sencillas al servicio de la cohesión y progresando, de manera acompañada, en la movilización de estrategias sencillas, individuales o grupales, de planificación, textualización y revisión.",
        "knowledgeCodes": [
          "LCL.2.A.4",
          "LCL.2.B.3.5",
          "LCL.2.D.5",
          "LCL.2.D.4"
        ]
      },
      {
        "code": "6.1.b",
        "competenceCode": "6",
        "text": "Localizar, seleccionar y contrastar información de distintas fuentes, con especial atención a las digitales, citándolas, evaluando su fiabilidad y recreándolas mediante la adaptación creativa de modelos.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "6.2.b",
        "competenceCode": "6",
        "text": "Compartir, de manera creativa, los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal o ecosocial, realizado de manera progresivamente autónoma.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "6.3.b",
        "competenceCode": "6",
        "text": "Adoptar hábitos sencillos de uso crítico, seguro, sostenible y saludable de las tecnologías digitales en relación con la búsqueda y la comunicación de la información, de manera progresivamente autónoma.",
        "knowledgeCodes": [
          "LCL.2.B.3.6"
        ]
      },
      {
        "code": "7.1.b",
        "competenceCode": "7",
        "text": "Leer con progresiva autonomía o de forma acompañada textos de diversos autores y autoras, ajustados a sus gustos e intereses y seleccionados con creciente autonomía, avanzando en la construcción de su identidad lectora para conseguir que sea una fuente de placer.",
        "knowledgeCodes": [
          "LCL.2.B.3.4",
          "LCL.2.B.3.6",
          "LCL.2.C.1",
          "LCL.2.C.6"
        ]
      },
      {
        "code": "7.2.b",
        "competenceCode": "7",
        "text": "Compartir la experiencia de lectura, en soportes diversos, participando en comunidades lectoras en el ámbito escolar para conseguir disfrutar de la dimensión social de la lectura.",
        "knowledgeCodes": [
          "LCL.2.C.2",
          "LCL.2.C.7",
          "LCL.2.C.9"
        ]
      },
      {
        "code": "8.1.b",
        "competenceCode": "8",
        "text": "Escuchar y leer, de manera acompañada, textos variados de la literatura infantil universal, que recojan diversidad de autores y autoras, relacionándolos en función de temas y aspectos elementales del género literario, e interpretándolos y relacionándolos con otras manifestaciones artísticas o culturales de manera acompañada.",
        "knowledgeCodes": [
          "LCL.2.C.1",
          "LCL.2.C.3",
          "LCL.2.C.5",
          "LCL.2.C.4",
          "LCL.2.C.7"
        ]
      },
      {
        "code": "8.2.b",
        "competenceCode": "8",
        "text": "Producir, de manera acompañada, textos sencillos individuales o colectivos con intención literaria, recreando de manera personal los modelos dados, en distintos soportes y complementándolos con otros lenguajes artísticos.",
        "knowledgeCodes": [
          "LCL.2.C.1",
          "LCL.2.C.3",
          "LCL.2.C.5",
          "LCL.2.C.8",
          "LCL.2.D.5",
          "LCL.2.D.6"
        ]
      },
      {
        "code": "8.3.b",
        "competenceCode": "8",
        "text": "Conocer y crear pequeños textos literarios a partir de pautas y modelos dados de la literatura tradicional andaluza.",
        "knowledgeCodes": [
          "LCL.2.B.2.1",
          "LCL.2.C.7"
        ]
      },
      {
        "code": "9.1.b",
        "competenceCode": "9",
        "text": "Formular conclusiones elementales sobre el funcionamiento de la lengua, utilizando la terminología elemental adecuada, prestando especial atención a la relación entre sustantivos, adjetivos y verbos, a partir de la observación, comparación y manipulación de palabras, enunciados y textos, en un proceso acompañado de producción o comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.2.D.1",
          "LCL.2.D.2"
        ]
      },
      {
        "code": "9.2.b",
        "competenceCode": "9",
        "text": "Revisar y mejorar los textos propios y ajenos y subsanar algunos problemas de comprensión lectora, de manera acompañada, a partir de la reflexión metalingüística e interlingüística y usando la terminología básica adecuada.",
        "knowledgeCodes": [
          "LCL.2.B.2.3",
          "LCL.2.B.3.5",
          "LCL.2.D.3",
          "LCL.2.D.5",
          "LCL.2.D.6",
          "LCL.2.D.7"
        ]
      },
      {
        "code": "10.1.b",
        "competenceCode": "10",
        "text": "Rechazar los usos lingüísticos discriminatorios e identificar los abusos de poder a través de la palabra a partir de la reflexión grupal acompañada sobre los aspectos básicos, verbales y no verbales, de la comunicación, teniendo en cuenta una perspectiva de género.",
        "knowledgeCodes": [
          "LCL.2.A.4",
          "LCL.2.B.3.1",
          "LCL.2.B.3.2",
          "LCL.2.B.3.4"
        ]
      },
      {
        "code": "10.2.b",
        "competenceCode": "10",
        "text": "Movilizar, con la planificación y el acompañamiento necesarios, estrategias básicas para la escucha activa, y la comunicación asertiva y el consenso, progresando en la gestión dialogada de conflictos.",
        "knowledgeCodes": [
          "LCL.2.B.1.1",
          "LCL.2.B.3.1"
        ]
      }
    ],
    "5": [
      {
        "code": "1.1.a",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto por las distintas lenguas y variedades dialectales, incluidas las lenguas de signos, identificando algunos rasgos de los dialectos y lenguas familiares del alumnado.",
        "knowledgeCodes": [
          "LCL.3.A.1",
          "LCL.3.A.2",
          "LCL.3.B.1.1"
        ]
      },
      {
        "code": "1.2.a",
        "competenceCode": "1",
        "text": "Detectar, con autonomía creciente y en contextos próximos, prejuicios y estereotipos lingüísticos frecuentes, aportando alternativas y valorando la diversidad lingüística del mundo como una fuente de riqueza cultural.",
        "knowledgeCodes": [
          "LCL.3.A.2",
          "LCL.3.A.3",
          "LCL.3.A.4"
        ]
      },
      {
        "code": "1.3.a",
        "competenceCode": "1",
        "text": "Conocer los rasgos de la modalidad lingüística andaluza del entorno geográfico del alumnado.",
        "knowledgeCodes": [
          "LCL.3.A.1",
          "LCL.3.A.2"
        ]
      },
      {
        "code": "2.1.a",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales y los mensajes explícitos e implícitos, valorando con cierta autonomía su contenido y los elementos no verbales elementales y, de manera acompañada, algunos elementos formales elementales.",
        "knowledgeCodes": [
          "LCL.3.B.2.3",
          "LCL.3.B.3.2",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.1.a",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales de manera progresivamente autónoma, coherente y fluida, en contextos formales sencillos y utilizando correctamente recursos verbales y no verbales básicos.",
        "knowledgeCodes": [
          "LCL.3.B.2.2",
          "LCL.3.B.3.2",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.2.a",
        "competenceCode": "3",
        "text": "Participar en interacciones orales espontáneas o regladas, respetando las normas de la cortesía lingüística, iniciando de manera acompañada el desarrollo de estrategias sencillas de escucha activa y de cooperación conversacional.",
        "knowledgeCodes": [
          "LCL.3.B.3.1",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.3.a",
        "competenceCode": "3",
        "text": "Conocer y producir textos orales y multimodales de manera progresivamente más autónoma, coherente y fluida, propios de la literatura infantil andaluza, utilizando correctamente recursos verbales y no verbales básicos.",
        "knowledgeCodes": [
          "LCL.3.B.3.2",
          "LCL.3.B.3.3",
          "LCL.3.C.1",
          "LCL.3.C.8"
        ]
      },
      {
        "code": "4.1.a",
        "competenceCode": "4",
        "text": "Leer de manera silenciosa y en voz alta textos escritos y multimodales sencillos, identificando el sentido global y la información relevante, realizando inferencias directas de manera acompañada y superando la interpretación literal para construir conocimiento.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.C.2",
          "LCL.3.C.6"
        ]
      },
      {
        "code": "4.2.a",
        "competenceCode": "4",
        "text": "Analizar e interpretar, de manera acompañada, el contenido y aspectos formales y no verbales elementales de textos escritos y multimodales, valorando su contenido y estructura e iniciando la evaluación de su calidad, fiabilidad e idoneidad en función del propósito de lectura.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "5.1.a",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales coherentes, en distintos soportes, seleccionando el modelo discursivo que mejor responda a cada situación comunicativa, progresando en el uso de las normas gramaticales y ortográficas básicas y movilizando, de manera acompañada, estrategias sencillas, individuales o grupales, de planificación, redacción, revisión y edición.",
        "knowledgeCodes": [
          "LCL.3.B.3.5",
          "LCL.3.B.3.6",
          "LCL.3.D.6",
          "LCL.3.D.7"
        ]
      },
      {
        "code": "6.1.a",
        "competenceCode": "6",
        "text": "Localizar, seleccionar y contrastar información de distintas fuentes, incluidas las digitales, citándolas, iniciándose en la evaluación de su fiabilidad y recreándolas mediante la adaptación creativa de modelos dados.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "6.2.a",
        "competenceCode": "6",
        "text": "Compartir de manera creativa los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal o ecosocial, realizado de manera acompañada.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "6.3.a",
        "competenceCode": "6",
        "text": "Adoptar hábitos sencillos de uso crítico, seguro, sostenible y saludable de las tecnologías digitales en relación con la búsqueda y la comunicación de la información.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "7.1.a",
        "competenceCode": "7",
        "text": "Leer de manera autónoma textos de diversos autores y autoras ajustados a sus gustos e intereses, seleccionados de manera puntualmente acompañada, progresando en la construcción de su identidad lectora para conseguir que sea una fuente de placer.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "7.2.a",
        "competenceCode": "7",
        "text": "Compartir la experiencia de lectura, en soportes diversos, participando en comunidades lectoras en el ámbito escolar o local para conseguir disfrutar de la dimensión social de la lectura.",
        "knowledgeCodes": [
          "LCL.3.C.3",
          "LCL.3.C.7",
          "LCL.3.C.10"
        ]
      },
      {
        "code": "8.1.a",
        "competenceCode": "8",
        "text": "Escuchar y leer textos literarios adecuados a su edad, que recojan diversidad de autores y autoras, relacionándolos en función de los temas y de aspectos elementales de cada género literario, e interpretándolos, iniciándose en la valoración de los mismos y relacionándolos con otras manifestaciones artísticas o culturales de manera progresivamente autónoma.",
        "knowledgeCodes": [
          "LCL.3.C.1",
          "LCL.3.C.4",
          "LCL.3.C.5",
          "LCL.3.C.9"
        ]
      },
      {
        "code": "8.2.a",
        "competenceCode": "8",
        "text": "Producir, de manera progresivamente autónoma, textos sencillos individuales o colectivos con intención literaria, reelaborando a partir de modelos dados y en distintos soportes y complementándolos con otros lenguajes artísticos.",
        "knowledgeCodes": [
          "LCL.3.C.1",
          "LCL.3.C.4",
          "LCL.3.C.5",
          "LCL.3.C.7",
          "LCL.3.D.4",
          "LCL.3.D.5"
        ]
      },
      {
        "code": "8.3.a",
        "competenceCode": "8",
        "text": "Conocer y crear textos literarios a partir de manifestaciones de la cultura popular andaluza orales y escritas, tales como refranes, cantinelas y poemas.",
        "knowledgeCodes": [
          "LCL.3.B.2.1",
          "LCL.3.C.6",
          "LCL.3.C.9"
        ]
      },
      {
        "code": "9.1.a",
        "competenceCode": "9",
        "text": "Formular generalizaciones sobre aspectos básicos del funcionamiento de la lengua de manera acompañada, utilizando la terminología elemental adecuada, formulando hipótesis y buscando contraejemplos, a partir de la observación, comparación y manipulación de palabras, enunciados y textos, en un proceso acompañado de producción o comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.3.D.1",
          "LCL.3.D.2",
          "LCL.3.D.7"
        ]
      },
      {
        "code": "9.2.a",
        "competenceCode": "9",
        "text": "Revisar los textos propios y ajenos y subsanar algunos problemas de comprensión lectora, de manera progresivamente autónoma, a partir de la reflexión metalingüística y usando la terminología básica adecuada.",
        "knowledgeCodes": [
          "LCL.3.B.2.3",
          "LCL.3.B.3.5",
          "LCL.3.D.3",
          "LCL.3.D.4",
          "LCL.3.D.5",
          "LCL.3.D.8"
        ]
      },
      {
        "code": "10.1.a",
        "competenceCode": "10",
        "text": "Rechazar los usos lingüísticos discriminatorios y los abusos de poder a través de la palabra identificados mediante la reflexión grupal acompañada sobre distintos aspectos, verbales y no verbales, de la comunicación, teniendo en cuenta una perspectiva de género.",
        "knowledgeCodes": [
          "LCL.3.A.4",
          "LCL.3.B.3.1",
          "LCL.3.B.3.2",
          "LCL.3.B.3.4"
        ]
      },
      {
        "code": "10.2.a",
        "competenceCode": "10",
        "text": "Iniciar, con la planificación y el acompañamiento necesarios, estrategias básicas para la deliberación argumentada y la gestión dialogada de conflictos, eligiendo soluciones entre varios modelos dados.",
        "knowledgeCodes": [
          "LCL.3.B.1.1",
          "LCL.3.B.3.1"
        ]
      }
    ],
    "6": [
      {
        "code": "1.1.b",
        "competenceCode": "1",
        "text": "Mostrar interés y respeto a las distintas lenguas y variedades dialectales, incluidas las lenguas de signos, identificando las características fundamentales de las de su entorno geográfico, así como algunos rasgos de los dialectos y lenguas familiares del alumnado.",
        "knowledgeCodes": [
          "LCL.3.A.1",
          "LCL.3.A.2",
          "LCL.3.B.1.1"
        ]
      },
      {
        "code": "1.2.b",
        "competenceCode": "1",
        "text": "Detectar, con autonomía creciente y en contextos próximos, prejuicios y estereotipos lingüísticos frecuentes, aportando alternativas y valorando la diversidad lingüística del mundo como una fuente de riqueza cultural.",
        "knowledgeCodes": [
          "LCL.3.A.2",
          "LCL.3.A.3",
          "LCL.3.A.4"
        ]
      },
      {
        "code": "1.3.b",
        "competenceCode": "1",
        "text": "Conocer los rasgos más destacados de la modalidad lingüística andaluza.",
        "knowledgeCodes": [
          "LCL.3.A.1",
          "LCL.3.A.2"
        ]
      },
      {
        "code": "2.1.b",
        "competenceCode": "2",
        "text": "Comprender el sentido de textos orales y multimodales sencillos, reconociendo las ideas principales y los mensajes explícitos e implícitos, valorando su contenido y los elementos no verbales elementales y, de manera acompañada, algunos elementos formales elementales.",
        "knowledgeCodes": [
          "LCL.3.B.2.3",
          "LCL.3.B.3.2",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.1.b",
        "competenceCode": "3",
        "text": "Producir textos orales y multimodales de manera autónoma, coherente y fluida, en contextos formales sencillos y utilizando correctamente recursos verbales y no verbales básicos.",
        "knowledgeCodes": [
          "LCL.3.B.2.2",
          "LCL.3.B.3.2",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.2.b",
        "competenceCode": "3",
        "text": "Participar en interacciones orales espontáneas o regladas, incorporando estrategias sencillas de escucha activa, de cortesía lingüística y de cooperación conversacional.",
        "knowledgeCodes": [
          "LCL.3.B.3.1",
          "LCL.3.B.3.3"
        ]
      },
      {
        "code": "3.3.b",
        "competenceCode": "3",
        "text": "Conocer y producir textos orales y multimodales de manera autónoma, coherente y fluida, propios de la literatura infantil andaluza, utilizando correctamente recursos verbales y no verbales básicos.",
        "knowledgeCodes": [
          "LCL.3.B.3.2",
          "LCL.3.B.3.3",
          "LCL.3.C.1",
          "LCL.3.C.8"
        ]
      },
      {
        "code": "4.1.b",
        "competenceCode": "4",
        "text": "Comprender el sentido global y la información relevante, de textos escritos y multimodales, realizando inferencias a partir de estrategias básicas de antes, durante y después de la lectura.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.C.2",
          "LCL.3.C.6"
        ]
      },
      {
        "code": "4.2.b",
        "competenceCode": "4",
        "text": "Analizar e interpretar, de manera acompañada, el contenido y aspectos formales y no formales elementales de textos escritos y multimodales, valorando su contenido y estructura y evaluando su calidad, fiabilidad e idoneidad en función del propósito de lectura.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "5.1.b",
        "competenceCode": "5",
        "text": "Producir textos escritos y multimodales de relativa complejidad, con coherencia y adecuación, en distintos soportes, progresando en el uso de las normas gramaticales y ortográficas básicas al servicio de la cohesión textual y movilizando estrategias sencillas, individuales o grupales, de planificación, textualización, revisión y edición.",
        "knowledgeCodes": [
          "LCL.3.B.3.5",
          "LCL.3.B.3.6",
          "LCL.3.D.6",
          "LCL.3.D.7"
        ]
      },
      {
        "code": "6.1.b",
        "competenceCode": "6",
        "text": "Localizar, seleccionar y contrastar información de distintas fuentes, incluidas las digitales, citándolas y recreándolas mediante la adaptación creativa de modelos dados.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "6.2.b",
        "competenceCode": "6",
        "text": "Compartir los resultados de un proceso de investigación sencillo, individual o grupal, sobre algún tema de interés personal o ecosocial, realizado de manera acompañada.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "6.3.b",
        "competenceCode": "6",
        "text": "Adoptar hábitos de uso crítico, seguro, sostenible y saludable de las tecnologías digitales en relación con la búsqueda y la comunicación de la información.",
        "knowledgeCodes": [
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "7.1.b",
        "competenceCode": "7",
        "text": "Leer de manera autónoma textos de diversos autores y autoras ajustados a sus gustos e intereses, seleccionados con criterio propio, progresando en la construcción de su identidad lectora para conseguir que sea una fuente de placer.",
        "knowledgeCodes": [
          "LCL.3.B.3.4",
          "LCL.3.B.3.6"
        ]
      },
      {
        "code": "7.2.b",
        "competenceCode": "7",
        "text": "Compartir la experiencia de lectura, en soportes diversos, participando en comunidades lectoras en el ámbito escolar o social para conseguir disfrutar de la dimensión social de la lectura.",
        "knowledgeCodes": [
          "LCL.3.C.3",
          "LCL.3.C.7",
          "LCL.3.C.10"
        ]
      },
      {
        "code": "8.1.b",
        "competenceCode": "8",
        "text": "Escuchar y leer de manera acompañada textos literarios adecuados a su edad, que recojan diversidad de autores y autoras, relacionándolos en función de los temas y de aspectos elementales de cada género literario, e interpretándolos, valorándolos y relacionándolos con otras manifestaciones artísticas o culturales de manera progresivamente autónoma.",
        "knowledgeCodes": [
          "LCL.3.C.1",
          "LCL.3.C.4",
          "LCL.3.C.5",
          "LCL.3.C.9"
        ]
      },
      {
        "code": "8.2.b",
        "competenceCode": "8",
        "text": "Producir, de manera progresivamente autónoma, textos sencillos individuales o colectivos con intención literaria, reelaborando con creatividad los modelos dados, en distintos soportes y complementándolos con otros lenguajes artísticos.",
        "knowledgeCodes": [
          "LCL.3.C.1",
          "LCL.3.C.4",
          "LCL.3.C.5",
          "LCL.3.C.7",
          "LCL.3.D.4",
          "LCL.3.D.5"
        ]
      },
      {
        "code": "8.3.b",
        "competenceCode": "8",
        "text": "Conocer y crear textos literarios a partir de manifestaciones de la cultura popular andaluza orales y escritas, tales como refranes, cantinelas y poemas, referenciando su validez histórica y los recursos estilísticos que contienen.",
        "knowledgeCodes": [
          "LCL.3.B.2.1",
          "LCL.3.C.6",
          "LCL.3.C.9"
        ]
      },
      {
        "code": "9.1.b",
        "competenceCode": "9",
        "text": "Establecer generalizaciones sobre aspectos básicos del funcionamiento de la lengua de manera puntualmente acompañada, utilizando la terminología elemental adecuada, formulando hipótesis y buscando contraejemplos, a partir de la observación, comparación y transformación de palabras, enunciados y textos, en un proceso acompañado de producción o comprensión de textos en contextos significativos.",
        "knowledgeCodes": [
          "LCL.3.D.1",
          "LCL.3.D.2",
          "LCL.3.D.7"
        ]
      },
      {
        "code": "9.2.b",
        "competenceCode": "9",
        "text": "Revisar y mejorar los textos propios y ajenos y subsanar algunos problemas de comprensión lectora, de manera progresivamente autónoma, a partir de la reflexión metalingüística e interlingüística y usando la terminología básica adecuada.",
        "knowledgeCodes": [
          "LCL.3.B.2.3",
          "LCL.3.B.3.5",
          "LCL.3.D.3",
          "LCL.3.D.4",
          "LCL.3.D.5",
          "LCL.3.D.8"
        ]
      },
      {
        "code": "10.1.b",
        "competenceCode": "10",
        "text": "Rechazar los usos lingüísticos discriminatorios y los abusos de poder a través de la palabra, identificados mediante la reflexión grupal, puntualmente acompañada, sobre distintos aspectos, verbales y no verbales, de la comunicación, teniendo en cuenta una perspectiva de género.",
        "knowledgeCodes": [
          "LCL.3.A.4",
          "LCL.3.B.3.1",
          "LCL.3.B.3.2",
          "LCL.3.B.3.4"
        ]
      },
      {
        "code": "10.2.b",
        "competenceCode": "10",
        "text": "Movilizar, con la planificación y el acompañamiento necesarios, estrategias básicas para la escucha activa, la comunicación asertiva y la deliberación argumentada, progresando en la gestión dialogada de conflictos, proponiendo soluciones creativas.",
        "knowledgeCodes": [
          "LCL.3.B.1.1",
          "LCL.3.B.3.1"
        ]
      }
    ]
  }
} as const;
